AllCops:
#  RunRailsCops: true
  Include:
  - '**/Gemfile'
  - '**/Rakefile'
  Exclude:
  - 'bin/*'
  - 'db/migrate/*'
  - 'db/seeds.rb'
  - 'db/schema.rb'
  - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Style/AsciiComments:
  Enabled: false